services:
  - type: web
    name: incisafe-manager-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: incisafe-manager-backend
          property: port
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false  # This will be set manually in Render dashboard
